### ISSUE TITLE
Support CASA image format

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue-astronomy#1]
spectral-cube supports reading casa's image format as of https://github.com/radio-astro-tools/spectral-cube/pull/541.  Glue should support reading these files.

Note that CASA images do not have a fixed extension, so the user needs to specify how these files are to be read.  That might require using the "Import Data" dialogue, or creating some other sort of popup dialogue.

**Comment by keflavich** [comment]
@astrofrog - should I be posting this here or back in main glue?

Also, this: https://github.com/glue-viz/glue/issues/1351 is probably not related despite the title being approximately the same

**Comment by astrofrog** [comment]
@keflavich - here makes sense, and I agree it would be great to support the CASA image format. I think if we can get the .ms reader to work it could go here too.

**Comment by astrofrog** [comment]
I'd like to avoid duplication of code, so it might make sense to simply delegate to spectral-cube here - however, will the spectral-cube reader fail for 2d images?

**Comment by keflavich** [comment]
I agree, delegate to spectral cube.  It works fine on 2d images.

**Comment by keflavich** [comment]
In the meantime, what's the fastest way to load something in glue via spectral-cube?  If I do:
```
cube = SpectralCube.read('cube.image', format='casa_image')
cube.to_glue()
```
it actually spins up a new instance of glue on top of the existing one, which isn't what I want (and probably means we should change something about the `to_glue` implementation).

**Comment by astrofrog** [comment]
Try going to 'Import Data' in glue and select 'FITS Spectral Cube' for the type, as I think it won't actually check the file is a FITS file:

https://github.com/glue-viz/glue/blob/9f8c2a567192f37f143d2133a0dff43738d4f99e/glue/plugins/data_factories/spectral_cube/spectral_cube.py#L50

(``is_spectral_cube`` does check if a file is FITS, but that's only used if trying to auto-guess the format)

**Comment by astrofrog** [comment]
This is now done and works with the latest developer version of glue and glue-astronomy. Docs being added in #6
