### ISSUE TITLE
Update Spectrum1D translator to preserve all coordinates

### ISSUE THREAD

**Issue by rosteen** [glue-viz/glue-astronomy#28]
[Specutils 754](https://github.com/astropy/specutils/pull/754) added some better cube handling to `Spectrum1D` by subclassing `NDCube`. We're now moving toward using `Spectrum1D` instead of `SpectralCube` in Jdaviz for handling cube datasets and immediately ran into the error seen in [Jdaviz 544](https://github.com/spacetelescope/jdaviz/issues/544), which appears to be caused by the translator only round-tripping the spectral axis rather than all coordinates defined by the WCS. We need the translator to handle the full WCS now, since we also care about the spatial coordinates.

I'm going to ask @javerbukh to open a draft PR in jdaviz so that others can reproduce the error trace he reported.

**Comment by astrofrog** [comment]
I agree that this should be fixed - note that glue coordinate objects can now just be any WCS or GWCS object so I think this should not be too difficult

**Comment by astrofrog** [comment]
I think this is now done.
