### ISSUE TITLE
Need 0.2 tag released on PyPI

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-astronomy#37]
This is blocking spacetelescope/jdaviz#711

**Comment by astrofrog** [comment]
Ah yes I forgot to do this after @eteq gave me the permissions to do it 😆  - I'll try and to today or tomorrow

**Comment by pllim** [comment]
Note: Still has not happened yet as of 2021-08-13.

**Comment by astrofrog** [comment]
Done!

**Comment by pllim** [comment]
Thanks!
