### ISSUE TITLE
Spectrum1D translator cannot handle spectral_axis in 3D cube

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-astronomy#60]
I am not sure what is the proper fix. I don't want to spend time hacking it only to be told it is wrong. Please advise. Thanks!

```python
import numpy as np
from astropy import units as u
from specutils import Spectrum1D

from glue_astronomy.translators.spectrum1d import Specutils1DHandler

sh = Specutils1DHandler()
spec = Spectrum1D(spectral_axis=np.arange(10) * u.pix, flux=np.ones((2, 2, 10)) * u.Jy)
obj = sh.to_data(spec)
```

```
.../glue_astronomy/translators/spectrum1d.py in to_data(self, obj)
    127         # Spectrum1D does it automatically on initialization.
    128         if len(obj.flux.shape) == 3:
--> 129             data = Data(coords=obj.wcs.swapaxes(-1, 0))
    130             data['flux'] = np.swapaxes(obj.flux, -1, 0)
    131             data.get_component('flux').units = str(obj.unit)

AttributeError: 'SpectralGWCS' object has no attribute 'swapaxes'
```

This is because when I pass `spectral_axis` into `Spectrum1D`, it creates a GWCS using https://github.com/astropy/specutils/blob/08de408d18d709a857b67e10ca2752d548eb3100/specutils/utils/wcs_utils.py#L185 and GWCS does not seem to understand `swapaxes`.

cc @astrofrog @rosteen 

This blocks spacetelescope/jdaviz#1040

Also see spacetelescope/gwcs#397

**Comment by astrofrog** [comment]
If only specutils did not mess with the axis order :laughing: 

One solution might be to add a model to the GWCS to reorder the axes, though @nden will have to give advice on this as I'm not familiar enough with GWCS.

**Comment by nden** [comment]
Here's the relevant discussion in gwcs: https://github.com/spacetelescope/gwcs/issues/269
IIRC I ran into difficulties due to the way the HighLevelWCSAPI was defined in astropy but I don't remember the details.

**Comment by rosteen** [comment]
@astrofrog I have a draft PR (https://github.com/glue-viz/glue-astronomy/pull/61) open to fix this but it needs more work. I'm going to tag you in some questions there in a moment.

**Comment by pllim** [comment]
Also might be relevant:

* spacetelescope/gwcs#397
