### ISSUE TITLE
How to use PaddedSpectrumWCS on 3D cube?

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-astronomy#75]
I have a 3D WCS but all I care about is to translate the spatial WCS (i.e., given a SkyCoord, I want X and Y pixel positions). I don't care about the spectral axis. In Cubeviz, the translator encodes the WCS as PaddedSpectrumWCS but I cannot figure out how to use it to grab just the spatial WCS object. I want to pass this spatial WCS to the [to_pixel method in a regions shape](https://github.com/astropy/regions/blob/660994fcec1ddd136900a3251e23174b1aaad0c6/regions/shapes/circle.py#L215).

This is as far as I got:

```python
from astropy.wcs import WCS
from specutils import Spectrum1D

from glue_astronomy.translators.spectrum1d import PaddedSpectrumWCS

flux = np.arange(16).reshape((2, 2, 4)) * u.Jy
wcs_dict = {"CTYPE1": "RA---TAN", "CTYPE2": "DEC--TAN", "CTYPE3": "WAVE",
            "CRVAL1": 205, "CRVAL2": 27, "CRVAL3": 1,
            "CDELT1": -0.0001, "CDELT2": 0.0001, "CDELT3": 8e-11,
            "CRPIX1": 0, "CRPIX2": 0, "CRPIX3": 0}
w = WCS(wcs_dict)

sp = Spectrum1D(flux=flux, wcs=w)

coords = PaddedSpectrumWCS(sp.wcs, sp.flux.ndim)
```

What should I do after this? Any ideas, @astrofrog or @dhomeier ?

**Comment by rosteen** [comment]
The WCS shouldn't be a `PaddedSpectrumWCS` if a cube with a 3D WCS is loaded, `PaddedSpectrumWCS` is specifically for the case where a cube with only a spectral WCS is loaded (generally due to creating a 3D `Spectrum1D` by providing a spectral axis but no WCS at all). So I don't understand how `PaddedSpectrumWCS` came to be relevant in this case.

**Comment by pllim** [comment]
TBH I don't remember what data triggered this 2 years ago. Maybe I should just close this issue.

**Comment by rosteen** [comment]
I should have replied sooner, sorry! 😅
